name = "PlantRayTracer"
uuid = "78485975-e4aa-407d-b3bb-ded5a4265d05"
authors = ["Alejandro Morales Sierra <alejandro.moralessierra@wur.nl> and contributors"]
version = "0.1.0"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlantGeomPrimitives = "7eef3cc5-4580-4ff0-8f6f-933507db6664"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[compat]
Atomix = "1.1.2"
CoordinateTransformations = "0.6.3"
LinearAlgebra = "1.11"
PlantGeomPrimitives = "0.1.0"
PrecompileTools = "1.3.3"
Random = "1.11"
Rotations = "1.5.1"
StaticArrays = "1.9.15"
Statistics = "1.11"
StatsBase = "0.34.6"
Unrolled = "0.1.5"
julia = "1.11"
